# Site settings
title: AI Research Documentation
description: A curated collection of AI tools, frameworks, and resources
baseurl: "/brain" # the subpath of your site, e.g. /blog
url: "https://wizardsupreme.github.io" 

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

# Theme settings
search_enabled: true
search:
  heading_level: 2
  previews: true
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/

# Navigation
aux_links:
  "View on GitHub":
    - "//github.com/wizardsupreme/brain"

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2024 wizard supreme. Distributed under an MIT license."

# Color scheme
color_scheme: dark

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green 