name: Nightly Release

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin main
          DIFF=$(git diff origin/main...dev)
          if [ -n "$DIFF" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge to main
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff dev -m "Release ${{ steps.date.outputs.date }}"
          git push origin main

      - name: Create Release Tag
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git tag v${{ steps.date.outputs.date }}
          git push origin v${{ steps.date.outputs.date }}

      - name: Create Release
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.date.outputs.date }}
          tag_name: v${{ steps.date.outputs.date }}
          body: |
            Automated release from dev branch
            Date: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false 